---
apiVersion: v1
kind: Service
metadata:
  name: tohatoha-app
  labels:
    app: tohatoha-app
spec:
  ports:
    - port: 8080
      targetPort: 3000
      protocol: TCP
  selector:
    app: tohatoha-app
    